name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 1.0.1
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^1.0.6
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  provider: ^4.0.1
  google_maps_webservice: ^0.0.16
  tuple: ^1.0.3
  http: ^0.12.0+4
  sqflite: ^1.3.2+1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
